import { makeStyles, Typography } from '@material-ui/core';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const useStyles = makeStyles({
  seen: {
    backgroundColor: 'red',
    fontSize: '20px',
  },
});

export default function Home() {
  const classes = useStyles();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography className={classes.seen}>hello</Typography>
    </div>
  );
}
